//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CA3_s00219815
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameConsoleDB : DbContext
    {
        public GameConsoleDB()
            : base("name=GameConsoleDB")
        {
        }
    
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Console> Consoles { get; set; }
    }
}
